### ISSUE TITLE
对小程序再开发的请求

### ISSUE THREAD

**Issue by huanghui2000** [changjunhao/colors-mp#1]
本人是哈尔滨某大学计算机系的学生，参加校内一个创新创业的比赛。
灵感原由https://colors.ichuantong.cn/  想做一个基于颜色和诗词的留言分享小程序。
发现已经被大神开发出来，想基于大神的版本进行改进和在开发，希望大神同意。

**Comment by changjunhao** [comment]
> 本人是哈尔滨某大学计算机系的学生，参加校内一个创新创业的比赛。 灵感原由https://colors.ichuantong.cn/ 想做一个基于颜色和诗词的留言分享小程序。 发现已经被大神开发出来，想基于大神的版本进行改进和在开发，希望大神同意。

可以，没问题的
